name: MSE-CICD

# Workflow Trigger
on:
  push:
    branches: [ "main" ]

# Default Working Directory
defaults:
  run:
    working-directory: rock-paper-scissor

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Setup
    - name: Checkout code into the Github Actions runner file system
      uses: actions/checkout@v2
    
    # Installing
    - name: Installing Java
      run: sudo apt-get update && sudo apt-get install -y openjdk-17-jdk
    - name: Installing Ant
      run: sudo apt-get install ant

    # Build & Test
    - name: Building
      run: ant compile
    - name: Testing
      run: ant test

    # Package
    - name: Packaging
      run: ant jar
