name: MSE-CICD

# Workflow Trigger
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Setup
    - name: Checkout code into the Github Actions runner file system
      uses: actions/checkout@v2
    
    # Installing
    - name: Installing Java
      run: sudo apt-get update && sudo apt-get install -y openjdk-17-jdk
    - name: Installing Ant
      run: sudo apt-get install ant

    # Build & Test
    - name: Building
      run: ant -buildfile rock-paper-scissor/build.xml compile
    - name: Testing
      working-directory: rock-paper-scissor
      run: ant -buildfile rock-paper-scissor/build.xml test

    # Package
    - name: Packaging
      working-directory: rock-paper-scissor
      run: ant -buildfile rock-paper-scissor/build.xml package
